language: rust
dist: trusty
sudo: true
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo clean
  - cargo build
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi  
