[package]
name = "sgbe"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]

[features]
nightly = []

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "gb"
path = "src/main.rs"

[dependencies]
failure = "0.1"
clap = "2.31"
log = "0.4"