[package]
name = "core"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]

[dev-dependencies]
hamcrest = "0.1"

[dependencies]
log = "0.4"
failure = "0.1"
smallvec = "0.6"
either = "1.5"
enumset = "0.3"